[env:esp8266]
platform = espressif8266
board = d1_mini
framework = arduino

board_build.filesystem = littlefs 

monitor_speed = 115200
board_build.flash_mode = dout

; Настройки для корректной работы встроенного терминала
monitor_filters = send_on_enter
monitor_echo = yes

; --- Настройки OTA (Раскомментировать после первой прошивки по кабелю) ---
; upload_protocol = espota
; upload_port = ВАШ_IP_АДРЕС_УСТРОЙСТВА
; upload_flags = --auth=YOUR_OTA_PASSWORD_HERE

lib_deps =
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    mathieucarbou/ESPAsyncWebServer @ ^3.3.23
    bblanchon/ArduinoJson @ ^6.21.5